name: CI/CD for .NET Core 8.0 Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up .NET
      - name: Setup .NET Core 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.100

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore SneakerSZN/SneakerSZN.sln

      # Run tests and generate code coverage
      - name: Run Tests with Coverage
        run: |
          mkdir -p TestResults
          dotnet test SneakerSZN/SneakerSZN.sln --no-restore --collect:"Code Coverage" \
          --results-directory TestResults --logger "trx;LogFileName=test_results.trx"

      # Install ReportGenerator
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      # Generate code coverage report in Cobertura format
      - name: Generate Coverage Report
        run: |
          reportgenerator \
          -reports:TestResults/**/*.xml \
          -targetdir:CoverageReports \
          -reporttypes:Cobertura

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t deanmichiels/sneakerbackend:latest -f SneakerSZN/SneakerSZN/Dockerfile SneakerSZN
          docker push deanmichiels/sneakerbackend:latest

      # Run SonarQube analysis
      - name: Run SonarQube Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Deantjeee_SneakerSZN-Backend
            -Dsonar.organization=deantjeee
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.cs.opencover.reportsPaths=CoverageReports/Cobertura.xml
