name: CI/CD for .NET Core 8.0 Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET
    - name: Setup .NET Core 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore SneakerSZN/SneakerSZN.sln

    # Run tests (continue on error)
    - name: Run Tests
      run: |
        dotnet test SneakerSZN/SneakerSZN.sln --no-restore || echo "Tests failed but continuing..."

    # Build the project
    - name: Build the project
      run: dotnet build SneakerSZN/SneakerSZN.sln --no-restore --configuration Release

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image
    - name: Build and Push Docker Image
      run: |
        docker build -t deanmiciels/sneakerbackend:latest SneakerSZN
        docker push deanmiciels/sneakerbackend:latest
