name: CI/CD for .NET Core 8.0 Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET
    - name: Setup .NET Core 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.100

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore SneakerSZN/SneakerSZN.sln

    # Run tests with result output
    - name: Run Tests
      run: |
        mkdir -p TestResults
        dotnet test SneakerSZN/SneakerSZN.sln --no-restore --logger "trx;LogFileName=TestResults/test_results.trx"
    # Build the project
    - name: Build the project
      run: dotnet build SneakerSZN/SneakerSZN.sln --no-restore --configuration Release

    # SonarQube Analysis
    - name: SonarQube Analysis
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=Deantjeee_SneakerSZN-Backend
          -Dsonar.organization=deantjeee
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.cs.opencover.reportsPaths=TestResults/test_results.trx
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push Docker image
    - name: Build and Push Docker Image
      run: |
        docker build -t deanmichiels/sneakerbackend:latest -f SneakerSZN/SneakerSZN/Dockerfile SneakerSZN
        docker push deanmichiels/sneakerbackend:latest
